# Generated by Django 6.0 on 2026-01-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='trailer',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
